name = "pixon-cloud"
main = "worker/index.mjs"
compatibility_date = "2026-10-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

routes = [
  { pattern = "pixon.com.mx/*", zone_name = "pixon.com.mx" },
  { pattern = "www.pixon.com.mx/*", zone_name = "pixon.com.mx" }
]

[assets]
directory = "./dist"

[[hyperdrive]]
binding = "HYPERDRIVE_FRESH"
id = "60f7f7cf1586446f8282986fb9d265c6"

[[hyperdrive]]
binding = "HYPERDRIVE_CACHED"
id = "e5532c69dec94e09bfee0c814c057c72"

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "pixon-media"

[[r2_buckets]]
binding = "BACKUP_BUCKET"
bucket_name = "pixon-backups"

[triggers]
crons = ["*/5 * * * *", "0 */6 * * *"]

[vars]
NODE_ENV = "production"
