'use strict';

const APPOINTMENT_TYPES = Object.freeze({
  DROP_OFF: 'DROP_OFF',
  PICKUP: 'PICKUP',
  DIAGNOSTIC: 'DIAGNOSTIC',
  MAINTENANCE: 'MAINTENANCE',
  REPAIR: 'REPAIR',
  LIQUID_DAMAGE: 'LIQUID_DAMAGE',
  ON_SITE: 'ON_SITE',
  BUSINESS: 'BUSINESS',
  REMOTE: 'REMOTE',
  OTHER: 'OTHER'
});

const APPOINTMENT_STATUSES = Object.freeze({
  TEMPORARY_HOLD: 'TEMPORARY_HOLD',
  PENDING_PAYMENT: 'PENDING_PAYMENT',
  CONFIRMED: 'CONFIRMED',
  CHECKED_IN: 'CHECKED_IN',
  DEVICE_RECEIVED: 'DEVICE_RECEIVED',
  IN_PROGRESS: 'IN_PROGRESS',
  CUSTOMER_ARRIVED: 'CUSTOMER_ARRIVED',
  DEVICE_DELIVERED: 'DEVICE_DELIVERED',
  COMPLETED: 'COMPLETED',
  RESCHEDULED: 'RESCHEDULED',
  CANCELLED_BY_CUSTOMER: 'CANCELLED_BY_CUSTOMER',
  CANCELLED_BY_ADMIN: 'CANCELLED_BY_ADMIN',
  NO_SHOW: 'NO_SHOW',
  EXPIRED: 'EXPIRED'
});

const ACTIVE_STATUSES = Object.freeze([
  APPOINTMENT_STATUSES.TEMPORARY_HOLD,
  APPOINTMENT_STATUSES.PENDING_PAYMENT,
  APPOINTMENT_STATUSES.CONFIRMED,
  APPOINTMENT_STATUSES.CHECKED_IN,
  APPOINTMENT_STATUSES.DEVICE_RECEIVED,
  APPOINTMENT_STATUSES.IN_PROGRESS,
  APPOINTMENT_STATUSES.CUSTOMER_ARRIVED
]);

const PAYMENT_STATUSES = Object.freeze({
  NOT_REQUIRED: 'NOT_REQUIRED',
  PENDING: 'PENDING',
  PAID: 'PAID',
  REFUNDED: 'REFUNDED',
  FORFEITED: 'FORFEITED',
  WAIVED: 'WAIVED'
});

const SLOT_STATES = Object.freeze({
  AVAILABLE: 'AVAILABLE',
  PARTIAL: 'PARTIAL',
  FULL: 'FULL',
  BLOCKED: 'BLOCKED'
});

const BLOCK_CATEGORIES = Object.freeze({
  PERSONAL: 'PERSONAL',
  OUT_OF_SHOP: 'OUT_OF_SHOP',
  PARTS_RUN: 'PARTS_RUN',
  INTERNAL_WORK: 'INTERNAL_WORK',
  INVENTORY: 'INVENTORY',
  MEAL: 'MEAL',
  TRAVEL: 'TRAVEL',
  UNAVAILABLE: 'UNAVAILABLE',
  OTHER: 'OTHER'
});

const SEMANTIC_COLORS = Object.freeze({
  AVAILABLE: '#10b981',       // Green
  PARTIAL: '#f59e0b',         // Amber / Yellow
  FULL: '#ef4444',            // Red
  BLOCKED: '#475569',         // Dark gray / slate
  PENDING_PAYMENT: '#f97316', // Orange
  CONFIRMED: '#0284c7',       // Blue / Navy Pixon
  ON_SITE: '#8b5cf6',         // Purple
  LIQUID_DAMAGE: '#dc2626'    // Special high-contrast red accent
});

module.exports = {
  APPOINTMENT_TYPES,
  APPOINTMENT_STATUSES,
  ACTIVE_STATUSES,
  PAYMENT_STATUSES,
  SLOT_STATES,
  BLOCK_CATEGORIES,
  SEMANTIC_COLORS
};
